/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ConexionBD;
import Controlador.ControllerProducto;
import static Vista.GestionDeUsuario.actor;
import static Vista.InicioSesion.frmenUsuario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sofiarodriguezmorales
 */
public class AñadirMovimiento extends javax.swing.JFrame {

    /**
     * Creates new form AñadirMovimiento
     */
     //conexion base de datos
    ConexionBD ventana = new ConexionBD();
    Connection cm = ventana.conexion();
    ControllerProducto sqlProductos = new ControllerProducto();

    PreparedStatement pst;
    String producto = "";
 
     
    public AñadirMovimiento() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jComboBoxMovimiento.addItem("Entrada");
        jComboBoxMovimiento.addItem("Salida");
        //FuncionesBaseDeDatos.DatabaseConnection();
    }
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButtonCategorias = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jButtonFiltroBusqueda3 = new javax.swing.JButton();
        jButtonProductos3 = new javax.swing.JButton();
        jLabelNombreProducto = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxMovimiento = new javax.swing.JComboBox<>();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldCantidadUnidades = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAñadirMovimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel.setForeground(new java.awt.Color(41, 113, 222));
        jLabel.setText("Añadir movimiento");

        jTextFieldDestino.setText("Ingrese destino");
        jTextFieldDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDestinoMouseClicked(evt);
            }
        });
        jTextFieldDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDestinoActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(41, 113, 222));

        jButtonCategorias.setBackground(new java.awt.Color(41, 113, 222));
        jButtonCategorias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCategorias.setText("Categorias");
        jButtonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriasActionPerformed(evt);
            }
        });

        jButtonUsuario.setBackground(new java.awt.Color(41, 113, 222));
        jButtonUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUsuario.setText("Usuario");
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });

        jButtonFiltroBusqueda3.setBackground(new java.awt.Color(41, 113, 222));
        jButtonFiltroBusqueda3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFiltroBusqueda3.setText("Filtro de busqueda");
        jButtonFiltroBusqueda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltroBusqueda3ActionPerformed(evt);
            }
        });

        jButtonProductos3.setBackground(new java.awt.Color(41, 113, 222));
        jButtonProductos3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProductos3.setText("Productos");
        jButtonProductos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductos3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonFiltroBusqueda3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonProductos3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonUsuario)
                .addGap(7, 7, 7)
                .addComponent(jButtonFiltroBusqueda3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProductos3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNombreProducto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelNombreProducto.setText("Nombre producto ");

        jLabelDestino.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelDestino.setText("Destino");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Cantidad de unidades");

        jLabelPrecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelPrecio.setText("Precio por unidad");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Movimiento");

        jComboBoxMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        jComboBoxMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMovimientoMouseClicked(evt);
            }
        });
        jComboBoxMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMovimientoActionPerformed(evt);
            }
        });

        jTextFieldPrecio.setText("Ingrese precio");
        jTextFieldPrecio.setToolTipText("");
        jTextFieldPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPrecioMouseClicked(evt);
            }
        });
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        jTextFieldCantidadUnidades.setText("Ingrese cantidad");
        jTextFieldCantidadUnidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCantidadUnidadesMouseClicked(evt);
            }
        });
        jTextFieldCantidadUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadUnidadesActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAñadirMovimiento.setBackground(new java.awt.Color(51, 204, 0));
        jButtonAñadirMovimiento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAñadirMovimiento.setText("Añdir movimiento");
        jButtonAñadirMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreProducto)
                            .addComponent(jLabel10))
                        .addGap(62, 62, 62)
                        .addComponent(jLabel7))
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDestino)
                            .addComponent(jComboBoxMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrecio)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jTextFieldCantidadUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAñadirMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelPrecio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDestino)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(jButtonAñadirMovimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addGap(350, 350, 350))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDestinoMouseClicked
        // TODO add your handling code here:
        jTextFieldDestino.setText(null);
    }//GEN-LAST:event_jTextFieldDestinoMouseClicked

    private void jButtonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriasActionPerformed
        // TODO add your handling code here:
        GestionDeCategoria GestionDeCategoria = new GestionDeCategoria();
        GestionDeCategoria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCategoriasActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            frmenUsuario = new GestionDeUsuario(actor);
            frmenUsuario.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AñadirUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonFiltroBusqueda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltroBusqueda3ActionPerformed
        FiltroDeBusqueda FiltroDeBusqueda = new FiltroDeBusqueda();
        FiltroDeBusqueda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFiltroBusqueda3ActionPerformed

    private void jButtonProductos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductos3ActionPerformed
        // TODO add your handling code here:
        GestionDeProducto GestionDeProducto = new GestionDeProducto();
        GestionDeProducto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonProductos3ActionPerformed

    private void jComboBoxMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMovimientoActionPerformed
        // TODO add your handling code here:
        if ("Entrada".equals(jComboBoxMovimiento.getSelectedItem().toString())){
            jTextFieldDestino.setVisible(false);
            jTextFieldPrecio.setVisible(true);
            jLabelDestino.setVisible(false);
            jLabelPrecio.setVisible(true);
            jTextFieldDestino.setText(" - ");
        }else if ("Salida".equals(jComboBoxMovimiento.getSelectedItem().toString())){
            jTextFieldPrecio.setVisible(false);
            jTextFieldDestino.setVisible(true);
            jLabelPrecio.setVisible(false);
            jLabelDestino.setVisible(true);
            
        }
    }//GEN-LAST:event_jComboBoxMovimientoActionPerformed

    private void jTextFieldDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDestinoActionPerformed

    private void jTextFieldPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMouseClicked
        jTextFieldDestino.setText(null);
    }//GEN-LAST:event_jTextFieldPrecioMouseClicked

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldCantidadUnidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCantidadUnidadesMouseClicked
        jTextFieldCantidadUnidades.setText(null);
    }//GEN-LAST:event_jTextFieldCantidadUnidadesMouseClicked

    private void jTextFieldCantidadUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadUnidadesActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        InfoProducto Producto = new InfoProducto();
        Producto.setVisible(true);
        Producto.MostrarInfo(producto);
        Producto.jLabelProducto.setText(producto);
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAñadirMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirMovimientoActionPerformed
       
        String cantidadUnidades = jTextFieldCantidadUnidades.getText();
        String destino = jTextFieldDestino.getText();
        String movimiento = jComboBoxMovimiento.getSelectedItem().toString();
        String cantidad = jTextFieldCantidadUnidades.getText();
        String precio = jTextFieldPrecio.getText();
        Integer cantidadActual = 0;
        
       int cantidadInt = 1;
       int precioInt = 1;

        //chequeo
        if (sqlProductos.chequeoMovimiento(jComboBoxMovimiento, jTextFieldCantidadUnidades, jTextFieldDestino, jTextFieldPrecio) == true){
            
            cantidadInt = sqlProductos.ConversionInteger(cantidad);
            precioInt = sqlProductos.ConversionInteger(precio);  
            
            try {
                InfoProducto Producto = new InfoProducto();
                
                
                pst = cm.prepareStatement("SELECT * FROM producto WHERE nombre = ?");
                pst.setString(1, jLabelNombreProducto.getText());
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    cantidadActual = rs.getInt("cantidad");
                }
                if (movimiento.equals("Salida") && cantidadActual - cantidadInt < 0){
                    JOptionPane.showMessageDialog(null, "La cantidad de unidades exceden al almacenado", "Error", JOptionPane.ERROR_MESSAGE);
                }else{
                    pst = cm.prepareStatement("INSERT INTO movimiento(categoria, producto, tipo, destino, cantidad, precio, usuario) VALUES (?,?,?,?,?,?,?) ");
                    pst.setString(1, Producto.getCategoria(jLabelNombreProducto.getText()));
                    pst.setString(2, jLabelNombreProducto.getText());
                    pst.setString(3, movimiento);
                    pst.setString(4, destino);
                    pst.setInt(5, cantidadInt);
                    pst.setInt(6, precioInt);     
                    pst.setString(7, actor.getUsuario());
                    pst.executeUpdate();
                    
                    if(movimiento.equals("Entrada")){
               
                   //suamr canridad
                   pst = cm.prepareStatement("UPDATE producto SET cantidad = cantidad + ? WHERE nombre = ?");
                   pst.setInt(1, cantidadInt);
                   pst.setString(2, jLabelNombreProducto.getText());
                   pst.executeUpdate();
                   
                   //cambio el precio unidad del producto
                   pst = cm.prepareStatement("UPDATE producto SET precioUnidad = ? WHERE nombre = ?");
                   pst.setInt(1, precioInt);
                   pst.setString(2, jLabelNombreProducto.getText());
                   pst.executeUpdate();
                   
                   //cambio precio total del producto
                   pst = cm.prepareStatement("UPDATE producto SET precioTotal = cantidad * ? WHERE nombre = ?");
                   pst.setInt(1, precioInt);
                   pst.setString(2, jLabelNombreProducto.getText());
                   pst.executeUpdate();
                   
               }else{
                   
                   //ressto cantidad
                   pst = cm.prepareStatement("UPDATE producto SET cantidad = cantidad - ? WHERE nombre = ?");
                   pst.setInt(1, cantidadInt);
                   pst.setString(2, jLabelNombreProducto.getText());
                   pst.executeUpdate();
                   
                    //cambio precio total del producto
                   pst = cm.prepareStatement("UPDATE producto SET precioTotal = precioTotal - (? * ?) WHERE nombre = ?");
                   pst.setInt(1, precioInt);
                   pst.setInt(2, cantidadInt);
                   pst.setString(3, jLabelNombreProducto.getText());
                   pst.executeUpdate();
               }
               
               //cambiar precio total del inventario
               
    
                
                Producto.setVisible(true);
                Producto.MostrarInfo(producto);
                Producto.jLabelProducto.setText(producto);
                this.dispose();
                JOptionPane.showMessageDialog(null,"Movimiento añadido satisfactoriamente");
                    
                    
                    
                }
                
               //chqueo si es entrada o salida para sumar o restar de la cantidad       
               
                  
            } catch (SQLException ex) {
                Logger.getLogger(AñadirCategoria.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Error de conexión con la base de datos");
            }
            
        }
        
        
       
    }//GEN-LAST:event_jButtonAñadirMovimientoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        producto = jLabelNombreProducto.getText();
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxMovimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMovimientoMouseClicked
        // TODO add your handling code here:
        
            
    }//GEN-LAST:event_jComboBoxMovimientoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirMovimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirMovimiento;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCategorias;
    private javax.swing.JButton jButtonFiltroBusqueda3;
    private javax.swing.JButton jButtonProductos3;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JComboBox<String> jComboBoxMovimiento;
    public javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDestino;
    public javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldCantidadUnidades;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
